### ISSUE TITLE
How to connect Neo4j with HTTPS

### ISSUE THREAD

**Issue by mingjinc** [sunjith/loopback-connector-neo4j-graph#3]
How to connect Neo4j with HTTPS & port 7473? 
As well, can we connect neo4j through bolt using loopback connector neo4j graph?

**Comment by sunjithps** [comment]
Hi,

You can connect with HTTPS using the url option in datasource.json like:
```
"neo4j": {
        "url": "https://username:password@localhost:7473",
        "name": "neo4j",
        "connector": "neo4j-graph"
}
```

**Comment by sunjithps** [comment]
No, it does not support bolt connection. You may want to fork it and use the bolt adapter (https://www.npmjs.com/package/node-neo4j-bolt-adapter) instead of node-neo4j and see if it works.

If you get it to work, feel free to submit a merge request. Thank you.

**Comment by mingjinc** [comment]
@sunjithps Great, Https works now. Thanks a lot :-)

**Comment by sunjithps** [comment]
@mingjinc Glad to know it works. You're welcome :-)
