### ISSUE TITLE
cannot update via replaceById 

### ISSUE THREAD

**Issue by tcalhounjr** [sunjith/loopback-connector-neo4j-graph#4]
This is the error I receive:

_The connector neo4j-graph does not support replaceById operation. This is not a bug in LoopBack. Please contact the authors of the connector, preferably via GitHub issues._

I cannot guarantee any of the property names will be unique. 

Any help with this would be greatly appreciated.

**Comment by sunjith** [comment]
Thank you for writing in Thomas. Shall look into this and get back to you in two days.

**Comment by sunjith** [comment]
Implemented replaceById operation. Shall be released after testing.

**Comment by tcalhounjr** [comment]
@sunjith Thanks!!!! Please make sure it's the loopback auto-generated ID and not the neo4j node ID because they're different. Also, please check out my next issue regarding using loopback model relations to build neo4j vertices between loopback models. This would be awesome making this connector fully functional!!!!

**Comment by sunjith** [comment]
Released the full update in version 1.1.1

**Comment by sunjith** [comment]
@tcalhounjr Yes, it shall be the loopback auto-generated ID and not the Neo4j node ID. I have responded to your other issue as well.
