### ISSUE TITLE
Cannot build relations using this connector

### ISSUE THREAD

**Issue by tcalhounjr** [sunjith/loopback-connector-neo4j-graph#5]
Model objects would work just like in MongoDB. However, relations will not be mapped to graph vertices as of now. Use cypher for creating vertices and graph queries.

Like, this is a problem especially if you're using React.js. How can I build relationships between my models?

**Comment by sunjith** [comment]
@tcalhounjr You cannot define relationships in models, you'll have to create them manually using Cypher queries in your code. If you would like to and have the bandwidth to implement the mapping between model relations to Neo4j graph vertices in the driver, feel free to send a pull request.
