### ISSUE TITLE
where do I add the code for creating vertices you suggested on the npm connector page

### ISSUE THREAD

**Issue by tcalhounjr** [sunjith/loopback-connector-neo4j-graph#6]
I'm building a React app so I get an error when I try to access the "ModelClass" because it's in common folder in the loopback portion of the app. This is the app error I'm receiving: 

_Module not found: You attempted to import ../../../common/models/person which falls outside of the project src/ directory. Relative imports outside of src/are not supported. You can either move it inside src/, or add a symlink to it from project's node_modules/._

Below is the code I added to one of my components that is, again, outside of the folder.

```
import {Person} from '../../../common/models/person';

myFunction() {
        Person.dataSource.connector.execute(
            "MATCH (n) RETURN n LIMIT 100",
            function (err, results) {
                if (err) {
                    throw err;
                } else {
                    // do something with results
                }
            }
        );
    }
```

My goal is to create a relationship between nodes when a user interacts with certain parts of the app. I've full CRUD capability (used Patch.../{id} to update) besides this one thing. Please, I beg of you, help me figure this out and I'll be the biggest evangelist of this connector!!!!

**Comment by sunjith** [comment]
@tcalhounjr This issue is outside the scope of this connector. However, I could personally give some suggestions. PM me.
